.gitignore, backend.py, readme.md, tkinter_designer.py
Most of the changes are to grammar and spelling.
I changed the "Success" notification from a `messagebox.askokcancel()` to a `messagebox.showinfo()` because it's a notification (nothing to cancel).
=> Fixed some grammar and spelling issues.

backend.py, tkinter_designer.py
These commits mainly focus on small issues such as...
* Output Path being appended to instead of overwritten
* `IndexError` when a user's design file doesn't have a Frame
* `generated_code` folder being created even when the program fails
There are two small code-structure changes:
* Moved local functions in `generate_code()` above variables
* Changed one pair of single-quotes to double-quotes
=> Small quality-of-life improvements.

backend.py, tkinter_designer.py
* **Changed the layout of output files**
* New layout puts all parameters on their own line
* This change improves output readability
* Ensures that lines don't end up extremely long
* Exempt from this are...
* `PhotoImage()`
* `x` and `y` coordinates
* Made sure that no lines extend beyond 79 characters
* Fixed awkward spacing and indentation
* Reworded comments more concisely
* Reworded error dialogs
* Renamed `path_to_save` as `output_path`
* Renamed `fileID` as `file_id` for consistency
* Added `strip()` to `token` and `link`
* This fixes an issue where spaces before/after any input would break the program
* Did not add to `generated_dir` because it worked with and without extra spaces
* Made sure that no **non-generated** lines extend beyond 79 characters
* Link in …
=> PEP 8 Compliance, minor re-wording, output readability improvements

readme.md
Updated instructions for installation
=> Update to readme.md

.github/ISSUE_TEMPLATE/key-error.md, .github/workflows/greetings.yml, readme.md
I made a couple corrections to fix misspellings, correct grammar, and other copyediting like capitalization and so forth. I didn't make any actual content changes, mainly because I just came across this project and haven't even installed it yet...
=> Minor spelling/grammar/copyediting changes

tkdesigner/figma/frame.py
Make sure to test it before merging.
=> Removed unnecessary element counter code

tkdesigner/figma/custom_elements.py, tkdesigner/figma/frame.py, tkdesigner/figma/node.py, tkdesigner/figma/vector_elements.py
- Added wrapping so the text on canvas is wrapped within the width of the element.
- Added casing for text.
=> Added case and wrapping support for text elements

.github/workflows/build.yml
Try to set version this way, idk if it will work, but worth a shot.
=> versioning nit

.github/workflows/build.yml, pyproject.toml
=> Ci nitpicks

.github/workflows/build.yml
Manual releases to github for now.
Git Tag your final commit on a PR. Merge will use this tag to release a version to pypi.
=> finalize version and publish step

pyproject.toml
https://pypi.org/project/cleo/
=> Fix the build: Add cleo to tool.poetry.dev-dependencies

docs/instructions.ar-DZ.md, docs/instructions.fr-FR.md, docs/instructions.gu-GU.md, docs/instructions.md, docs/instructions.tr-TR.md, docs/instructions.zh-CN.md, tkdesigner/figma/frame.py, tkdesigner/figma/vector_elements.py
This PR add support to Line element into Figma
=> Feat line element

docs/README.pt-BR.md
Hi Community Tkinter-Designer!
1. I am sending the Readme.pt-Br.md file that is translated in ptbr that I promised.
2. I hope to help community: Tkinter-Designer.
=> Add README.pt-BR.md 

docs/instructions.pt-BR.md
=> Add instructions.pt-BR.md

gui/gui.py
fix a question: AttributeError: module 'tkinter' has no attribute 'messagebox'
=> fix a question: AttributeError: module 'tkinter' has no attribute 'messagebox'

gui/gui.py
=> Modification of "x" value in title.place and info_text

docs/README.kr-KR.md, docs/instructions.kr-KR.md, docs/instructions.md
Hello. I like your project and hope to contribute a little. I translated it into Korean. 
Thank you!
=> korean translation added

README.md, docs/README.vi-VN.md, docs/instructions.md, docs/instructions.vi-VN.md
This pull request aims to enhance the project's accessibility and user experience by adding a Vietnamese translation for the entire README and instruction documentation. By providing a localized version in Vietnamese, we enable a wider audience to understand and engage with the project.
The Vietnamese translation includes a comprehensive translation of the project's introduction, usage instructions, examples, showcase, license, contribution guidelines, contact information, and more. It ensures that Vietnamese-speaking users can fully comprehend the features, benefits, and functionalities offered by the project.
This contribution not only benefits Vietnamese-speaking users but also strengthens the project as a whole. It demonstrates the collaborative and community-driven nature of …
=> Added Vietnamese Translation for the Project

docs/instructions.md, tkdesigner/figma/custom_elements.py, tkdesigner/figma/frame.py
I am submitting this pull request to propose a new feature for Tkinter-Designer, which is a Button Hover effect. The way it works is very simple. I have added a new element named `ButtonHover` and a class with the same name to convert the the element into a button with a hover effect.
The main class that generates the code for the hover effect is called `ButtonHover`. The `ButtonHover` class is designed to generate code for creating a hover effect on a button. It takes in three parameters: a node, a frame, and an image_path. The node and frame parameters specify the position of the button on the canvas, while the image_path parameter specifies the path to the image that will be displayed when the button is hovered over.
To create the hover effect, the `ButtonHover` class needs to know the …
=> Added Button hover effect

docs/README.pt-BR.md, docs/instructions.pt-BR.md
Fixed typos;
Translated leftover words in English;
Updated README.pt-BR.md to newer version.
=> Updated pt-BR translations
